up

diff --git a/.github/workflows/r2r-js-sdk-integration-tests.yml b/.github/workflows/r2r-js-sdk-integration-tests.yml
--- a/.github/workflows/r2r-js-sdk-integration-tests.yml
+++ b/.github/workflows/r2r-js-sdk-integration-tests.yml
@@ -16,42 +16,42 @@ jobs:
     steps:
       - uses: actions/checkout@v2
 
-      - name: Set up Python
-        uses: actions/setup-python@v2
-        with:
-          python-version: "3.x"
+      # - name: Set up Python
+      #   uses: actions/setup-python@v2
+      #   with:
+      #     python-version: "3.x"
 
-      - name: Install R2R
-        run: |
-          python -m pip install --upgrade pip
-          pip install r2r
+      # - name: Install R2R
+      #   run: |
+      #     python -m pip install --upgrade pip
+      #     pip install r2r
 
-      - name: Start R2R server
-        env:
-          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
-        run: |
-          r2r serve --docker
-          sleep 60
+      # - name: Start R2R server
+      #   env:
+      #     OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
+      #   run: |
+      #     r2r serve --docker
+      #     sleep 60
 
-      - name: Use Node.js
-        uses: actions/setup-node@v2
-        with:
-          node-version: "20.x"
+      # - name: Use Node.js
+      #   uses: actions/setup-node@v2
+      #   with:
+      #     node-version: "20.x"
 
-      - name: Install dependencies
-        run: npm ci
+      # - name: Install dependencies
+      #   run: npm ci
 
-      - name: Check if R2R server is running
-        run: |
-          curl http://localhost:7272/v2/health || echo "Server not responding"
+      # - name: Check if R2R server is running
+      #   run: |
+      #     curl http://localhost:7272/v2/health || echo "Server not responding"
 
-      - name: Display R2R server logs if server not responding
-        if: failure()
-        run: docker logs r2r-r2r-1
+      # - name: Display R2R server logs if server not responding
+      #   if: failure()
+      #   run: docker logs r2r-r2r-1
 
-      - name: Run integration tests
-        run: npm run test
+      # - name: Run integration tests
+      #   run: npm run test
 
-      - name: Display R2R server logs if tests fail
-        if: failure()
-        run: docker logs r2r-r2r-1
+      # - name: Display R2R server logs if tests fail
+      #   if: failure()
+      #   run: docker logs r2r-r2r-1
